Headless render
measuredco/puck pull request #197
Opened 2023-11-01 04:17 UTC by 4leite

2023-11-02 02:47 UTC, 4leite commented
Closing in favor of #199

2023-11-02 02:48 UTC, 4leite commented
Closing in favor of #199

2023-11-02 11:06 UTC, chrisvxd commented
Thanks @4leite! This is in my queue to review soon. Sorry for slow response.

Feel free to join us [on discord](https://discord.gg/D9e4E3MQVZ) if you want to chat more in-depth about this, too.

2023-11-07 12:28 UTC, chrisvxd commented on packages/core/components/ServerRender/index.tsx
> +}
This needs prettier formatting before linting will succeed

2023-11-07 12:28 UTC, chrisvxd commented on packages/core/rsc.tsx
> +export { Render } from "./components/ServerRender";
This needs prettier formatting before linting will succeed

2023-11-07 13:26 UTC, 4leite commented
> ... but I wonder if we should consider a breaking change to the `DropZone` API, enforcing the use of `renderDropZone` instead of `<DropZone>` and updating the existing `Render` component to avoid context.

As implemented it's opt in, but yes I feel like deprecating the existing Dropzone api and removing it later is a good option. I'm interested if anyone has any use case for the context rendered Dropzone that this doesn't solve.
 
> I'm not ready to make a call on this yet, but would value any input on how that might work (especially regarding the modules).

There's no way around having separate modules for the rsc renderer that I can see using cjs. It's maybe doable but complicated with esm and preserve modules. The issue is it's one file, and nextjs sees the hooks and other client code in the file so it marks it as needing "use client" above it in the tree. Exporting the renderer as part of the main module will still work fine for those not trying to optimise for static server rendered content.

2023-11-07 18:40 UTC, chrisvxd requested changes
Thanks for the clarity @4leite. I've been thinking about this some more and think your proposal is the best option.

Going with ESM doesn't really buy us anything, as we still need to split the output into separate files. That's the only way RSC is going to behave, so file-denominated bundling is the way to go.

We can do a follow on to deprecate the legacy DropZone API, and capture the breaking change in #202.

I've left a few comments before we merge.

2023-11-07 18:40 UTC, chrisvxd commented on packages/core/components/DropZone/index.tsx
> +                  puckCtx: { renderDropZone: DropZone },
I find `puckCtx` a bit awkward, and think `ctx` (aka "context") is a bit of a misnomer.

What about simply `puck`?

```suggestion
                  puck: { renderDropZone: DropZone },
```

2023-11-07 23:16 UTC, 4leite commented on packages/core/types/Config.tsx
> +type RootComponentConfig<
I actually created this to resolve an issue I had - was unaware RootComponentConfig was ever in main.
But it highlighted a bug a missed -  the implementation did not support using renderDropZone in a root component.

Have removed the type difference and fixed the bug.

2023-11-07 23:21 UTC, 4leite commented on packages/core/components/Render/index.tsx
> -
@chrisvxd  Render now uses the ServerRender component, just wrapping in context for backwards compatibility

2023-11-08 08:52 UTC, 4leite commented
hmm, looks like the server render is not working in the demo app. Will have a look, but might need to walk back the change to use ServerRender in the Render component

2023-11-08 22:07 UTC, chrisvxd approved these changes
I'm thinking we may actually want to keep DropZones as-is (rather than deprecating), but we don't need to make that decision here. Going to merge. Awesome stuff, @4leite!

2023-11-08 22:07 UTC, chrisvxd commented
@4leite seems like it needs a rebase before I can merge

2023-11-10 14:05 UTC, merged