feat: array field element duplicate functionality
measuredco/puck pull request #676
Opened 2024-11-04 07:12 UTC by siarhei-zharnasek

First of all, thanks for such awesome library.

For some purposes it's useful to have duplicate functionality not only for the whole component but also for Array field element itself.

<img width="249" alt="image" src="https://github.com/user-attachments/assets/fbcc4754-f13a-45c0-a741-289a2013fd8a">

2024-11-07 18:16 UTC, chrisvxd requested changes
Great feature! Thank you for adding it. I left some comments.

Once you've address, I'll hold off merging until we're closer to v0.17.

2024-11-14 09:12 UTC, siarhei-zharnasek commented on packages/core/components/AutoField/fields/ArrayField/index.tsx
> +                                  <div className={getClassNameItem("action")}>
sure, my bad
changed order

2024-11-14 09:13 UTC, siarhei-zharnasek commented on packages/core/components/AutoField/fields/ArrayField/index.tsx
> +                                          mapArrayStateToUi(regenerateArrayState(existingValue))
okay, done

2024-11-14 16:17 UTC, chrisvxd approved these changes
🎉

2024-11-14 16:18 UTC, merged